services:
 qa_app:
   restart: always
   build:
     context: .
     dockerfile: Dockerfile
   container_name: qa_app
   env_file:
     - .env
   ports:
     - "${APP_PORT}:${APP_PORT}"
   volumes:
     - ./app:/qa_app/app
     - ./alembic:/qa_app/alembic
   depends_on:
     - postgres
   networks:
     - qa_network

 postgres:
   restart: always
   image: postgres:16.4-alpine
   container_name: qa_db
   command: postgres
   env_file:
     - .env
   ports:
     - "${POSTGRES_EXTERNAL_PORT}:${POSTGRES_PORT}"
   volumes:
     - ./postgres/data:/var/lib/postgresql/data
     - ./postgres/backups:/backups
   networks:
     - qa_network

networks:
  qa_network:
    driver: bridge

volumes:
  local-storage:
